apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-placeholder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SEU_USUARIO/platform-infra.git
    targetRevision: main
    path: k8s/addons/helmfile/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }