ingressController:
  installCRDs: false

proxy:
  type: NodePort
  http:
    enabled: true
    servicePort: 80
    nodePort: 30080
  tls:
    enabled: false

admin:
  enabled: true
  type: NodePort
  http:
    enabled: true
    servicePort: 8001
    nodePort: 32080

# Exposição de métricas do Kong
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kube-prometheus-stack

plugins:
  bundled: true

env:
  log_level: info
  database: "off"              # DB-less (config via CRDs)
  nginx_worker_processes: "2"
  admin_listen: 0.0.0.0:8001
  plugins: bundled, prometheus, cors, rate-limiting, jwt
