loki:
  enabled: true
  isDefault: true
  auth_enabled: false
  persistence:
    enabled: false

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.monitoring.svc:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri: {}
        - labels:
            app: |
              if (.kubernetes.labels.app) { .kubernetes.labels.app } else { "" }
        - output:
            source: message
  serviceMonitor:
    enabled: true

grafana:
  enabled: false
