apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-servicemonitor
  namespace: kong
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kong
  namespaceSelector:
    matchNames: ["kong"]
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
